### ISSUE TITLE
Windows - app stops/disconnects with Custom(EOF) right after connecting to debug server

### ISSUE THREAD

**Issue by jcward** [jcward/vscode-hxcpp-debug#18]
Currently crashing with Custom(EOF) before receiving files lists:

![image](https://cloud.githubusercontent.com/assets/2192439/11789402/691e8e26-a253-11e5-9255-580364e45d12.png)

**Comment by hughsando** [comment]
It looks like the socket has been closed.
This looks like it might be https://github.com/HaxeFoundation/hxcpp-debugger/blob/master/debugger/HaxeRemote.hx#L92
or maybe the thread stopping for some reason here:
https://github.com/HaxeFoundation/hxcpp-debugger/blob/master/debugger/DebuggerThread.hx#L284

If you put some traces in, you might get a better idea of who is asking the debug thread to terminate.

**Comment by jcward** [comment]
Hmm, the app is still crashing after @hughsando's Array join fix (https://github.com/HaxeFoundation/hxcpp/commit/2ba105ad8b7380bdc76e0808a2b3482ba1ea9e3c).

![image](https://cloud.githubusercontent.com/assets/2192439/12805183/9d38b8f4-cab6-11e5-8e6b-cf06e0e1408a.png)

**Comment by jcward** [comment]
I believe this was fixed with #25 / PR #31
