### ISSUE TITLE
DebugAdapter not found - mac

### ISSUE THREAD

**Issue by lewislepton** [jcward/vscode-hxcpp-debug#21]
hello,

this popped once i had tried to run the mac part in VSCode

<img width="876" alt="screen shot 2015-12-16 at 18 08 04" src="https://cloud.githubusercontent.com/assets/11299322/11849487/10379e0a-a420-11e5-8fd9-b4565595ce20.png">

**Comment by jcward** [comment]
Hi @lewislepton - thanks, I've added a note in the readme about this specific error message. You need to build the debug adapter with:
```
cd vscode-hxcpp-debug
haxe build-mac.hxml
```
This produces the `bin/mac/vschxcppdb` executable that VSCode is expecting.

Let me know if this doesn't solve the issue for you. Cheers!

**Comment by lewislepton** [comment]
ah hahahaha. thanks. will try ;)
