### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by kiroukou** [jcward/vscode-hxcpp-debug#24]
Hi,
First, thank you for that attempt ! Sounds amazing and I really enjoy the idea to finally have a good cross-platform IDE for haxe.

I've managed to get few things done right I guess, but I end up with this error : 
_"Debug adapter process has terminated unexpectedly"_

I do not really know what do that mean...

I have the latest haxelib hxcpp version
THe launch json file is almost the same one there's in the openfl sample
``` json
{
	"version": "0.1.0",
	"configurations": [
		{
			"runtimeExecutable": "${execPath}",
			"args": [
				"compilePath=${workspaceRoot}",
				"compileCommand=haxelib run openfl build windows -debug -DHXCPP_DEBUGGER",
				"runPath=${workspaceRoot}/bin/windows/cpp/bin/",
				"runCommand=smileyFight",
				"runInTerminal=false"
			],
			"name": "Build and debug",
			"type": "hxcpp",
			"request": "launch",
			"stopOnEntry": true
		},
		{
			"runtimeExecutable": "${execPath}",
			"args": [
				"runPath=${workspaceRoot}/bin/windows/cpp/bin/",
				"runCommand=smileyFight",
				"runInTerminal=false"
			],
			"name": "Debug",
			"type": "hxcpp",
			"request": "launch",
			"program": "",
			"stopOnEntry": true
		}
	]
}
```

Do you have an idea?

Thanks !
Thomas

**Comment by jcward** [comment]
Hi Thomas,

It looks like your on Windows -- I haven't gotten it working fully on windows yet. But your error message means the debug adapter crashed (not your app, which also happens on windows.)

But you can maybe get some debug information. If you create a `C:\tmp` folder, the adapter will create `C:\tmp\adapter.log` so you can see what it's doing, maybe see the last output before it crashed. Then post maybe the last 10 or 20 lines of that log.

**Comment by kiroukou** [comment]
Hello.
Yes I'm on windows at work indeed.
I've created the tmp directory, but nothing is written inside it after the failure.

I investigate a bit on my side

**Comment by jcward** [comment]
Hmm, maybe it's permissions? It worked on windows when I created that directory...

**Comment by kiroukou** [comment]
Also, VSC display a warning on my launch.json file  on the type field.
Currently it is set with "hxcpp" and the warning says :
![capture](https://cloud.githubusercontent.com/assets/2912939/12203611/14a9c4be-b630-11e5-8793-44624ebec495.PNG)

**Comment by jcward** [comment]
Yes, that warning a known issue with vscode and nothing to worry about: https://github.com/Microsoft/vscode/issues/546

Hmm, I'll be able to help investigate later today after work.

**Comment by kiroukou** [comment]
Ok thanks.

In case it can help, _.vscode\extensions\vscode-hxcpp-debug\bin\windows\Options.txt_
HX_UTF8_STRINGS=1
debugger=1.1.0
haxe3=1
haxe_ver=3.201
hxcpp=3.2.205
hxcpp_api_level=321
windows=1
hxcpp=C:\Projects\motionTools\haxe3\lib/hxcpp/3,2,205/

**Comment by kiroukou** [comment]
Ok, that was due to a problem with my hxcpp version...
Sorry for the inconvenience !

I may come back anytime soon with some other issues :) I'm really looking forward this project.
Best
Thomas

**Comment by jcward** [comment]
Awesome, glad you got it figured out! Like I said, I think you'll run into more trouble -- I haven't gotten it fully working on Windows yet, but I appreciate your feedback!
