### ISSUE TITLE
Linux compile error: JsonPrinter.cpp - hx_getEnumValueIndex’ was not declared  

### ISSUE THREAD

**Issue by cambiata** [jcward/vscode-hxcpp-debug#39]
I'm on Ubuntu Gnome 15.10, Haxe 3.3-RC1, Hxcpp 3.3.49.
When trying to compile vscode-hxcpp-debug (>haxe build-linux.hxml), I get the following error:

Error: While running :g++ -I/home/jonas/Downloads/vscode-hxcpp-debug-master/bin/linux/obj/linux64/__pch/haxe -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=330 -m64 -DHXCPP_M64 -I/home/jonas/haxelib/hxcpp/3,3,49/include -x c++ -frtti -Wno-invalid-offsetof ./src/haxe/format/JsonPrinter.cpp -o/home/jonas/Downloads/vscode-hxcpp-debug-master/bin/linux/obj/linux64/80c0ed55_JsonPrinter.o
./src/haxe/format/JsonPrinter.cpp: In member function ‘void haxe::format::JsonPrinter_obj::write(Dynamic, Dynamic)’:
./src/haxe/format/JsonPrinter.cpp:81:53: error: ‘_hx_getEnumValueIndex’ was not declared in this scope
 HXDLIN(  81)   switch((int)(_hx_getEnumValueIndex(_g))){
                                                     ^
Error: Build failed

Any idea?

Jonas

**Comment by jcward** [comment]
Interesting, I'm using a development git version of haxe from June 24, and hxcpp 3.3.49, it compiles fine, and my `bin/linux/src/haxe/format/JsonPrinter.cpp` at line 81 looks different than yours -- it doesn't have `_hx_getEnumValueIndex`:

```
HXLINE(  81)			HX_VARI( ::hx::EnumBase,_g) = ::Type_obj::_hx_typeof(v);
HXDLIN(  81)			Int _hx_tmp1 = ( ( ::hx::EnumBase)(_g) )->_hx_getIndex();
HXDLIN(  81)			switch((int)(_hx_tmp1)){
```

**Comment by waneck** [comment]
If you are using the latest Haxe version, you also need the dev hxcpp
version. `_hx_getEnumValueIndex` will be there!

2016-08-23 16:33 GMT-03:00 Jeff Ward <notifications@github.com>:

**Comment by cambiata** [comment]
Thanks, Caue! That solved the problem!
