### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by NenadBojkovski** [jcward/vscode-hxcpp-debug#43]
Hi guys.

I'm experiencing  "Debug adapter process has terminated unexpectedly" when I add a break point usually in the recursive methods. 
I have installed VS Code 1.4.0  and the hxcpp debugger. I have macOs Sierra. The Options.txt file have these values (the versions of hxcpp and hxcpp-debugger are correct).

HX_UTF8_STRINGS=1
haxe3=1
haxe_ver=3.3
hxcpp=3.3.49
hxcpp-debugger=1.2.0
hxcpp_api_level=330
hxcpp_debugger=1.2.0
mac=1
source-header=Generated by Haxe 3.3.0
hxcpp=/Users/nenad/haxelib/hxcpp/3,3,49/

The Terminal output has this error:
Debugger:Failed to read command from server at localhost:6972: Eof
Debugger:An error occurred on the write thread loop (sending messages to the debugger): Null Object Reference
Debugger:Closing connection.
Called from debugger.HaxeRemote::new debugger/HaxeRemote.hx line 71
Called from debugger.HaxeRemote::writeThreadLoop debugger/HaxeRemote.hx line 145
Critical Error: Uncatchable Throw: An error occurred on the write thread loop (sending messages to the debugger): Null Object Reference

I see that it fails with EOF error when it tries to read next command from the server, but I don't understand why it happens.

Anyone have any idea ?

**Comment by jcward** [comment]
Hmm, this error message is coming out of the debugger (the low-level code that's injected into your project) -- I think the issue belongs on that project:

https://github.com/HaxeFoundation/hxcpp-debugger

It's possible that vscode-hxcpp-debug is using the debugger incorrectly, so maybe leave this issue open for now and reference it from the issue you file over there?

**Comment by NenadBojkovski** [comment]
Thanks for the reply! I'll do that.

**Comment by tanis2000** [comment]
@NenadBojkovski it looks like I'm hitting this same problem. I'll have a look into it.

**Comment by tanis2000** [comment]
A fresh clone of hxcpp-debugger from git and a recompile actually did the trick. So I guess it's just a stale version of hxcpp-debugger or the HaxeServer that isn't staying up. I've been running HaxeServer from the command line and it works a charm.

**Comment by jcward** [comment]
Thanks for the notes, @tanis2000. I'll go ahead and close this.
