### ISSUE TITLE
Removing breakpoint doesn't work

### ISSUE THREAD

**Issue by jcward** [jcward/vscode-hxcpp-debug#50]
Looking at adapter.log, it appears I'm always sending `AddFileLineBreakpoint` commands. I need to keep a local representation of "added" breakpoints, then remove them when the list is updated.

e.g. on adding breakpoint at line 19, vscode sends me:

```
{"command":"setBreakpoints","arguments":{"source":{"name":"/Main.hx","path":"/home/jward/dev/vscode-hxcpp-debug/test cli/Main.hx"},"lines":[19],"breakpoints":[{"line":19}],"sourceModified":false},"type":"request","seq":24}
```

And I send: `AddFileLineBreakpoint(Main.hx,19)`

Adding on 24:

```
{"body":{"breakpoints":[{"verified":true,"line":19},{"verified":true,"line":24}]},"command":"setBreakpoints","success":true,"request_seq":23,"type":"response"}
```

And I send: `AddFileLineBreakpoint(Main.hx,19)` `AddFileLineBreakpoint(Main.hx,24)`

Then removing 24:
```
{"command":"setBreakpoints","arguments":{"source":{"name":"/Main.hx","path":"/home/jward/dev/vscode-hxcpp-debug/test cli/Main.hx"},"lines":[19],"breakpoints":[{"line":19}],"sourceModified":false},"type":"request","seq":24}
```

And I send: `AddFileLineBreakpoint(Main.hx,19)`

I need to maintain state and send [DeleteFileLineBreakpoint](https://github.com/HaxeFoundation/hxcpp-debugger/blob/master/debugger/DebuggerThread.hx#L211-L212).

**Comment by jcward** [comment]
TODO: `UNHANDLED MESSAGE: BreakpointStatuses(Terminator)` Does hxcpp-debugger move breakpoints on invalid lines? I don't think so...

**Comment by JohnSword** [comment]
ok it's now possible to remove the breakpoints at runtime but then it's not possible to set them back at the same line if need be.

**Comment by jcward** [comment]
Interesting, thanks for the note @JohnSword, I'll check that out.

**Comment by jcward** [comment]
Got it. Thanks for keeping me on my toes, @JohnSword!
