### ISSUE TITLE
Mac debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by jasonsturges** [jcward/vscode-hxcpp-debug#52]
So excited to discover this project - this is just awesome.  Exactly what I've been looking for.

On Mac, my debug adapter process terminates unexpectedly.  After caught in the debugger, stepping over appears unpredictable, then crashes.  

![vscode](https://cloud.githubusercontent.com/assets/1213591/24334330/e5696672-122d-11e7-88ea-3ed1ee0c51b6.gif)

Presumably I've not set this up correctly - any ideas of what I could try?

**Comment by jasonsturges** [comment]
Some additional detail - if I have a breakpoint set upon launch of the debugger, it immediately crashes; however, after the debugger starts (as above) if I then set breakpoints I can continue and step into code with good results.  

Step over and step out are not reaching code I would expect, though, and ultimately crashes.

**Comment by jcward** [comment]
Thanks for the report. Interesting. In cases of a hard crash of your app, the stack trace may provide the most interesting information. Here's a glimpse of it in your gif:

![image](https://cloud.githubusercontent.com/assets/2192439/24366789/7168bee4-12d7-11e7-8a82-98ec92dab156.png)

I'm not that familiar with OSX, but if you build your app with the right debug settings, these could point to a specific location in cpp files, perhaps something in the hxcpp runtime or hxcpp-debugger code.

Crashes of the app itself are *usually* not the fault of the debug adapter -- it merely told the hxcpp-debugger to step forward. You could isolate this by running the debugger in "local / cli" mode. Here's an example of me running the hxcpp-debugger in local mode (aka, outside vscode, though I haven't actually done this with an OpenFL app): https://github.com/HaxeFoundation/hxcpp-debugger/issues/17#issuecomment-287453492

**Comment by jasonsturges** [comment]
On Mac, the debugger doesn't gracefully detach from the process - it terminates the executing environment.  That abnormal exit produces the same result as force quit of the Haxe process.  Both VSCode and IntelliJ error even pressing the stop-button.  Sorry, I didn't think that through.

Here, there's more than the detach, though - when I execute from my own shell:

![screen-capture](https://cloud.githubusercontent.com/assets/1213591/24370736/1959d384-12ee-11e7-88c5-723521895e05.gif)

The console reports:

```
Debugger:Failed to read command from server at localhost:6972: Eof
Debugger:An error occurred on the write thread loop (sending messages to the debugger): Null Object Reference
Debugger:Closing connection.
Called from debugger.HaxeRemote::new debugger/HaxeRemote.hx line 71
Called from hxcpp::__hxcpp_main
Called from debugger.HaxeRemote::writeThreadLoop debugger/HaxeRemote.hx line 145
Called from ApplicationMain::main ApplicationMain.hx line 78
Critical Error: Uncatchable Throw: An error occurred on the write thread loop (sending messages to the debugger): Null Object Reference
Called from ApplicationMain::create ApplicationMain.hx line 108
Called from lime.app.Preloader::load lime/app/Preloader.hx line 207
```

Stack trace:

```
Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

Thread 0:: Dispatch queue: com.apple.main-thread
0   com.jasonsturges.labs.benchmark	0x0000000107f27ae9 hx::FormatStack(char const*, char const*, char const*, int, bool) + 105 (Debug.cpp:117)
1   com.jasonsturges.labs.benchmark	0x0000000107f28a17 hx::ExceptionStackFrame::format(bool) + 103 (Debug.cpp:421)
2   com.jasonsturges.labs.benchmark	0x0000000107f28921 hx::ExceptionStackFrame::toDisplay() + 33 (Debug.cpp:424)
3   com.jasonsturges.labs.benchmark	0x0000000107f288c8 hx::StackContext::dumpExceptionStack() + 88 (Debug.cpp:363)
4   com.jasonsturges.labs.benchmark	0x0000000107f27a4e hx::CriticalErrorHandler(String, bool) + 174 (Debug.cpp:83)
5   com.jasonsturges.labs.benchmark	0x0000000107f27995 hx::CriticalError(String const&, bool) + 53 (Debug.cpp:107)
6   com.jasonsturges.labs.benchmark	0x0000000107f2c950 __hxcpp_dbg_checkedThrow(Dynamic) + 144 (Debugger.cpp:1452)
7   com.jasonsturges.labs.benchmark	0x0000000107f28b24 hx::NullReference(char const*, bool) + 244 (Debug.cpp:440)
8   com.jasonsturges.labs.benchmark	0x0000000107f5c4c9 Dynamic::ThrowBadFunctionError() + 25 (Dynamic.cpp:519)
9   com.jasonsturges.labs.benchmark	0x000000010707d53f Dynamic::CheckFPtr() + 31 (Dynamic.h:298)
10  com.jasonsturges.labs.benchmark	0x000000010707e41f Dynamic::operator()(Dynamic const&, Dynamic const&) + 47 (Dynamic.h:302)
11  com.jasonsturges.labs.benchmark	0x0000000107f2d199 hx::DebuggerContext::DoBreak(hx::DebugStatus, int, String const*) + 617 (Debugger.cpp:316)
12  com.jasonsturges.labs.benchmark	0x0000000107f3240c hx::DebuggerContext::Break(hx::DebugStatus, int, String const*) + 124 (Debugger.cpp:338)
13  com.jasonsturges.labs.benchmark	0x0000000107f2ce54 hx::Breakpoints::HandleBreakpoints(hx::StackContext*) + 772 (Debugger.cpp:672)
14  com.jasonsturges.labs.benchmark	0x0000000107f2cb25 __hxcpp_on_line_changed(hx::StackContext*) + 21 (Debugger.cpp:1471)
15  com.jasonsturges.labs.benchmark	0x0000000107ed07c0 openfl::events::EventDispatcher_obj::_hx___dispatchEvent(hx::ObjectPtr<openfl::events::Event_obj>) + 3792 (EventDispatcher.cpp:293)
```

Thanks for the recommendation - I'll give it a go, and report back with any additional information.

**Comment by jasonsturges** [comment]
This problem was exclusively hxcpp - updating my local haxelib to HaxeFoundation/hxcpp@4e4aab7 resolved all problems.  Ultimately had nothing to do with your debug adapter.

Thanks for all the insight - tracing the problem, and this local cli debugger is great knowledge that I'm sure I will be referencing again.

This adapter is truly a wish come true - exactly what I've wanted for years.

**Comment by jcward** [comment]
@jasonsturges - ah, glad you got it sorted out. Hmm, that rev is the latest release (as of now) in the [nightlies](http://nmehost.com/hxcpp/), hxcpp 3.4.78.

There still could be a more graceful detachment, but I think that's more of a feature at this point.

Thanks!
