### ISSUE TITLE
can't debug "test cli"

### ISSUE THREAD

**Issue by r3d9u11** [jcward/vscode-hxcpp-debug#61]
Hi. I tried to debug sample "test cli", but have output message:
```
Compile succeeded!
Launching application...
Client not yet connected, does it 1) call new HaxeRemote(true, 'localhost'), 2) compiled with -debug, and 3) define -D HXCPP_DEBUGGER ?
```
![123](https://user-images.githubusercontent.com/15020827/31851070-24e23e54-b667-11e7-8bda-39b93b9016d8.png)

what I'm doing wrong?
Thanks.

**Comment by jcward** [comment]
That means the `test cli` program is not connecting to the vscode debugger after we launch it. Since we see that, if you used [build.hxml](https://github.com/jcward/vscode-hxcpp-debug/blob/master/test%20cli/build.hxml), it has the necessary `-debug` and `-D HXCPP_DEBUGGER`, we then start to question whether the socket communication is working.

Also, what version of hxcpp are you using? One known working combo (on linux64) was haxe 3.4.2 and hxcpp 3.4.90.

**Comment by r3d9u11** [comment]
@jcward I'm using haxe 3.4.4 and hxcpp 3.4.188, I'll try to downgrade hxcpp

**Comment by r3d9u11** [comment]
@jcward haxelib don't contain version 3.4.90 of hxcpp :( https://lib.haxe.org/p/hxcpp/versions/

**Comment by jcward** [comment]
You can find 3.4.90 from Hugh's build server: http://nmehost.com/hxcpp/

**Comment by r3d9u11** [comment]
@jcward tried with hxcpp 3.4.90, but it doesn't effect:

```
Compiling group: haxe
g++ -Iinclude -c -fvisibility=hidden -g -fpic -fPIC -DHX_LINUX -DHXCPP_DEBUG -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_STACK_TRACE(haxe) -DHXCPP_TELEMETRY(haxe) -DHXCPP_DEBUGGER(haxe) -DHXCPP_API_LEVEL=331(haxe) -m64 -DHXCPP_M64 -I/home/user/.haxelib_repo/hxcpp/3,4,90/include ... tags=[haxe,static]
 - src/Main.cpp 
Link: Main-debug
Compile succeeded!
Launching application...
Client not yet connected, does it 1) call new HaxeRemote(true, 'localhost'), 2) compiled with -debug, and 3) define -D HXCPP_DEBUGGER ?
```

probably troubles with haxe 3.4.4 (latest stable version in [official haxe's ppa repo](https://launchpad.net/~haxe/+archive/ubuntu/releases))

**Comment by r3d9u11** [comment]
@jcward I think something wrong with installed extension. I have notice for my launch.json: file:
 ```
'file:///home/user/Desktop/hxdbg/.vscode/launch.json'
severity: 'Warning'
message: 'The debug type is not recognized. Make sure that you have a corresponding debug extension installed and that it is enabled.'
at: '13,12'
source: ''
```
But extension is already installed (from git):
![vscode](https://user-images.githubusercontent.com/15020827/32167520-22ce203c-bd7a-11e7-9114-557fddbff898.png)

**Comment by r3d9u11** [comment]
@jcward also I tried [VSCode 1.7.2](https://code.visualstudio.com/updates/v1_7), but without success

**Comment by r3d9u11** [comment]
@jcward I don't understand whats wrong. type "hxcpp" available for empty configuration:
![screen1](https://user-images.githubusercontent.com/15020827/32170230-e260ceea-bd84-11e7-8692-b51efaeac01d.png)

but the type "hxcpp" was hidden after parameter "args" is setted up
![screen2](https://user-images.githubusercontent.com/15020827/32170292-09845564-bd85-11e7-946e-6cc7c82249ad.png)

any ideas?

**Comment by r3d9u11** [comment]
@jcward I'm tried it again. Problem was solved: for linux just needed gnome-terminal. Please, note about it in the readme ;-)
